import Head from "next/head";
import Image from "next/image";
import Navbar from "../Components/Navbar";
import styles from "../styles/Home.module.css";
import React, { useEffect } from "react";
import Smart1 from "../styles/images/orange-icon-removebg-preview.png";
import Smart2 from "../styles/images/peach-icon-removebg-preview.png";
import Smart3 from "../styles/images/guava-icon-removebg-preview.png";
import Smart4 from "../styles/images/loquat-icon-removebg-preview.png";
import F1 from "../styles/images/orange-service-removebg-preview.png";
import F2 from "../styles/images/peach-removebg-preview.png";
import F3 from "../styles/images/amrood-services-removebg-preview.png";
import F4 from "../styles/images/loquat-services-removebg-preview.png";
import icon1 from "../styles/images/icon1.png";
import icon2 from "../styles/images/icon2.png";
import icon3 from "../styles/images/icon3.png";
import icon4 from "../styles/images/icon4.png";
import food from "../styles/images/why.jpg";
import Product1 from "../styles/images/CaraNavelOgrange.jpg";
import Product2 from "../styles/images/SweetOrange.jpg";
import Product3 from "../styles/images/amrood.jpg";
import Product4 from "../styles/images/loquat.jpg";
import Product5 from "../styles/images/peach.jpg";
import Testimonials from "../Components/Testimonials";
import Icon from "../styles/images/709605.png";
import Contactus from "../Components/Contactus";
import Footer from "../Components/Footer";
import AOS from "aos";
import "aos/dist/aos.css";
import Link from "next/link";

export default function Home() {
	useEffect(() => {
		AOS.init({
			duration: 2000,
		});
	}, []);
	return (
		<div>
			<Head>
				<title>Majid Fruit Farms</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div
				className="u-body u-overlap u-overlap-contrast u-overlap-transparent u-xl-mode"
				data-lang="en"
			>
				<section
					className="u-align-left u-clearfix u-image u-shading u-section-1"
					id="carousel_5ad0"
					data-image-width="1782"
					data-image-height="1080"
				>
					<Navbar />
					<div className="u-clearfix u-sheet u-sheet-1">
						<h1 className="u-align-left u-text u-text-palette-3-base u-text-1">
							Majid Farms and Fruits Supplier (It’s all about you!)
						</h1>
						<p className="u-text u-text-body-alt-color u-text-3">
							MFFS is a grower, packer, and supplier. We have a dedicated team
							of qualified professionals committed to producing high-quality
							products. We offer a variety of fruits, vegetables, and herbal
							teas on a wholesale and retail basis, including but not limited to
							Blood Red Oranges, California Peaches, Spanish Loquats, Guavas,
							and Olives. So why wait? Give us a call and place your order, and
							we will be happy to serve you as we believe it’s all about you!
							<b>
								<i>
									“
									<span className="u-text-palette-3-base">
										Foods and Services Portfolio.
									</span>
								</i>
							</b>
						</p>
						<a
							href="tel:+92-3459371589"
							className="u-active-white u-border-2 u-border-hover-white u-border-white u-btn u-button-style u-hover-white u-none u-text-active-black u-text-body-alt-color u-text-hover-palette-1-base u-btn-1"
						>
							Call Now
						</a>
					</div>
				</section>
			</div>

			<div className="conatiner">
				<h2 className="text-center">Our Products</h2>
				<div className="row justify-center" data-aos="zoom-in-up">
					<div className="col-md-5">
						<div
							class="card product-bg1"
							style={{ width: "15rem;", height: "15rem" }}
						>
							<a>
								<Link href="/Services">
									<div class="card-body text-center mt-[4rem]">
										<h2 class="card-title " style={{ color: "white" }}>
											Oranges
										</h2>
									</div>
								</Link>
							</a>
						</div>
					</div>
					<div className="col-md-5">
						<div
							class="card product-bg2"
							style={{ width: "15rem;", height: "15rem" }}
						>
							<a>
								<Link href="/Services">
									<div class="card-body text-center mt-[4rem]">
										<h2 class="card-title " style={{ color: "white" }}>
											Guava
										</h2>
									</div>
								</Link>
							</a>
						</div>
					</div>
					<div className="col-md-5 mt-[3rem]">
						<div
							class="card product-bg3"
							style={{ width: "15rem;", height: "15rem" }}
						>
							<a>
								<Link href="/Services">
									<div class="card-body text-center mt-[4rem]">
										<h2 class="card-title " style={{ color: "white" }}>
											Loquat
										</h2>
									</div>
								</Link>
							</a>
						</div>
					</div>
					<div className="col-md-5 mt-[3rem]">
						<div
							class="card product-bg4"
							style={{ width: "15rem;", height: "15rem" }}
						>
							<a>
								<Link href="/Services">
									<div class="card-body text-center mt-[4rem]">
										<h2 class="card-title " style={{ color: "white" }}>
											Peaches
										</h2>
									</div>
								</Link>
							</a>
						</div>
					</div>
				</div>
			</div>

			<Contactus />
			<Footer />
		</div>
	);
}
